src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToMany(targetEntity: Course::class, mappedBy: 'Students')]
    private $courses;

    #[ORM\OneToOne(inversedBy: 'student', targetEntity: User::class, cascade: ['persist', 'remove'])]
    private $User;

    #[ORM\ManyToOne(targetEntity: Department::class, inversedBy: 'Students')]
    private $department;

    #[ORM\OneToMany(mappedBy: 'Student', targetEntity: Submission::class)]
    private $submissions;

    public function __construct()
    {
        $this->courses = new ArrayCollection();
        $this->submissions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Course>
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Course $course): self
    {
        if (!$this->courses->contains($course)) {
            $this->courses[] = $course;
            $course->addStudent($this);
        }

        return $this;
    }

    public function removeCourse(Course $course): self
    {
        if ($this->courses->removeElement($course)) {
            $course->removeStudent($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;

        return $this;
    }

    /**
     * @return Collection<int, Submission>
     */
    public function getSubmissions(): Collection
    {
        return $this->submissions;
    }

    public function addSubmission(Submission $submission): self
    {
        if (!$this->submissions->contains($submission)) {
            $this->submissions[] = $submission;
            $submission->setStudent($this);
        }

        return $this;
    }

    public function removeSubmission(Submission $submission): self
    {
        if ($this->submissions->removeElement($submission)) {
            // set the owning side to null (unless already changed)
            if ($submission->getStudent() === $this) {
                $submission->setStudent(null);
            }
        }

        return $this;
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Assignment;
use App\Entity\Course;
use App\Entity\Department;
use App\Entity\Lecture;
use App\Entity\Student;
use App\Entity\Submission;
use App\Repository\AssignmentRepository;
use App\Repository\CourseRepository;
use App\Repository\DepartmentRepository;
use App\Repository\FacultyRepository;
use App\Repository\StudentRepository;
use App\Repository\SubmissionRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/student')]
class StudentController extends AbstractController
{
    #[Route('/', name: 'app_student')]
    public function index(AssignmentRepository $assignmentRepository): Response
    {
        return $this->render('learning/student/index.html.twig', [
            'controller_name' => 'StudentController',
            'assignments' => $assignmentRepository->findPendingAssignmentsForStudent($this->getUser()->getStudent())
        ]);
    }
    #[Route('/courses', name: 'app_student_courses')]
    public function Courses(): Response
    {
        return $this->render('learning/student/courses.html.twig', [
            'controller_name' => 'StudentController',
        ]);
    }
    #[Route('/courses/search', name: 'app_student_courses_search', methods: ["POST"])]
    public function SearchCourses(Request $request, CourseRepository $courseRepository): Response
    {
        return $this->render('learning/student/courses_search.html.twig', [
            'courses' => $courseRepository->findCourses($request->request->get('searchTerm'))
        ]);
    }
    #[Route('/courses/{course}', name: 'app_student_course')]
    public function Course(Course $course, CourseRepository $courseRepository): Response
    {
        /* @var $student Student*/
        $student = $this->getUser()->getStudent();
        return $this->render('learning/student/course.html.twig', [
            'course' => $course, 'enrolled'=>$courseRepository->studentEnrolled($course, $student)
        ]);
    }
    #[Route('/courses/{course}/enroll', name: 'app_student_course_enroll', methods: ["POST"])]
    public function CourseEnroll(ManagerRegistry $registry, Course $course): Response
    {
        /* @var $student Student*/
        $student = $this->getUser()->getStudent();
        $student->addCourse($course);
        $entityManager = $registry->getManager();
        $entityManager->persist($student);
        $entityManager->flush();
        return $this->redirectToRoute('app_student_course',['course'=> $course->getId()]);
    }
    #[Route('/assignments', name: 'app_student_assignments')]
    public function Assignments(): Response
    {
        return $this->render('learning/student/assignments.html.twig', [
            'controller_name' => 'StudentController',
        ]);
    }
    #[Route('/assignment/{assignment}', name: 'app_student_assignment')]
    public function Assignment(Assignment $assignment, CourseRepository $courseRepository, SubmissionRepository $submissionRepository): Response
    {
        /* @var $student Student*/
        $student = $this->getUser()->getStudent();
        $course = $assignment->getCourseWeek()->getCourse();
        $submission = $submissionRepository->findOneBy(["Student" => $student, "Assignment" => $assignment]);
        return $this->render('learning/student/assignment.html.twig', [
            'controller_name' => 'StudentController',
            'assignment'=> $assignment, 'enrolled'=>$courseRepository->studentEnrolled($course, $student),
            'submission' => $submission
        ]);
    }

    #[Route('/assignment/{assignment}/submit', name: 'app_student_assignment_submit')]
    public function AssignmentSubmit(Request $request, Assignment $assignment, SubmissionRepository $submissionRepository): Response
    {
        /* @var $student Student*/
        $student = $this->getUser()->getStudent();
        $submission = $submissionRepository->findOneBy(["Student" => $student, "Assignment" => $assignment]);
        if($submission){
            $submission->setFiler($request->request->get('file'));
        }
        else{
            $submission = new Submission();
            $submission->setFiler($request->request->get('file'));
            $submission->setAssignment($assignment);
            $submission->setStudent($student);
        }
        $submission->setSubmitDate(new \DateTimeImmutable());
        $submissionRepository->add($submission, true);
        return $this->redirectToRoute('app_student_assignment',['assignment'=> $assignment->getId()]);
    }
    #[Route('/lecture/{lecture}', name: 'app_student_lecture')]
    public function Lecture(Lecture $lecture, CourseRepository $courseRepository): Response
    {
        /* @var $student Student*/
        $student = $this->getUser()->getStudent();
        $course = $lecture->getCourseWeek()->getCourse();
        return $this->render('learning/student/lecture.html.twig', [
            'controller_name' => 'StudentController', 'lecture' => $lecture, 'enrolled'=>$courseRepository->studentEnrolled($course, $student)
        ]);
    }
    #[Route('/enroll', name: 'app_student_enroll')]
    public function Enroll(Request $request, DepartmentRepository $departmentRepository, FacultyRepository $facultyRepository, StudentRepository $studentRepository): Response
    {
        $department = $request->request->get('department');
        if($department){
            $department = $departmentRepository->find($department);
            $student = new Student();
            $student->setDepartment($department);
            $student->setUser($this->getUser());
            $studentRepository->add($student, true);
            return $this->redirectToRoute('app_student');
        }

        return $this->render('learning/student/enroll.html.twig', [
            'controller_name' => 'StudentController',
            'faculties' => $facultyRepository->findAll(),
            'departments' => $departmentRepository->findAll()
        ]);
    }
}

templates/learning/student/assignment.html.twig
{% extends 'learning/index.html.twig' %}

{% block title %}{{ assignment.title }}{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}
        {% if enrolled %}
        <h2> {{ assignment.title }}</h2>
        <div class="list-group">
            <div class="col-md-6 px-0">
                <h3 >Information</h3>
                <p class="lead my-3">{{ assignment.description }}</p>
            </div>
            <div class="accordion" id="accordionFile" style="height: 100px">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingFile">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFile" aria-expanded="true" aria-controls="collapseFile">
                            Downloads
                        </button>
                    </h2>
                    <div id="collapseFile" class="accordion-collapse collapse show" aria-labelledby="headingFile" data-bs-parent="#accordionFile">

                        <ol class="list-group ">
                            {% if assignment.file %}
                                <a href="{{ assignment.file }}" class="list-group-item d-flex justify-content-between align-items-start">
                                    <div class="ms-2 me-auto">
                                        <div class="fw-bold">Assignment Resources</div>
                                    </div>
                                </a>
                            {% else %}
                                <p class="ms-2 me-auto">No Downloads Available!</p>
                            {% endif %}
                        </ol>
                    </div>
                </div>
            </div>
            <div class="accordion" id="accordionSubmit" style="height: 100px">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingSubmit">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSubmit" aria-expanded="true" aria-controls="collapseSubmit">
                            Submission
                        </button>
                    </h2>
                    <div id="collapseSubmit" class="accordion-collapse collapse show" aria-labelledby="headingSubmit" data-bs-parent="#accordionSubmit">

                        <form method="post" action="{{ path('app_student_assignment_submit', {assignment: assignment.id}) }}">
                        <div class="p-3 col-md-6 mb-3">
                            {% if submission%}
                                {% if submission.grade %}
                                    <button type="button" class="btn btn-primary">
                                        Grade <span class="badge text-bg-secondary">{{ submission.grade }}</span>
                                    </button>
                                {%  else %}
                                    <label for="exampleFormControlInput1" class="form-label">File:</label>
                                    <textarea name="file" type="text" class="form-control" id="exampleFormControlInput1">{{ submission.filer }}</textarea>
                                    <br/>
                                    <button class="btn btn-primary mb-3">Resubmit</button>
                                {% endif %}
                            {% else %}
                                <textarea name="file" type="text" class="form-control" id="exampleFormControlInput1"></textarea>
                                <br/>
                                <button class="btn btn-primary mb-3">Submit</button>
                            {% endif %}
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <form method="post" action="{{ path('app_student_course_enroll', {course: assignment.courseweek.course.id}) }}">
        <button class="btn btn-primary mb-3">Enroll</button>
        </form>
        {% endif %}

        {% else %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You haven't enrolled as a student, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student_enroll') }}" class="text-white fw-bold">Enroll</a></p>
                </div>
            </div>
        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}

templates/learning/student/assignments.html.twig
{% extends 'learning/index.html.twig' %}

{% block title %}Assignments{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}
            <h2> My Courses</h2>
            <div class="list-group">
                {% for course in app.user.student.courses %}
                    {% for assignment in course.Assignments %}
                        <a href="{{ path('app_student_assignment', {assignment: assignment.id}) }}" class="list-group-item list-group-item-action" aria-current="true">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ assignment.title }}</h5>
                                <small>Week {{ assignment.courseweek.cardinality }}</small>
                            </div>
                            <p class="mb-1">{{ assignment.course.title }}</p>
                            <small>Department of {{ assignment.course.department.name }}</small>
                        </a>
                    {% else %}
                        <div class="col-md-6 px-0">
                            <p class="lead my-3">No Assignments!</p>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="col-md-6 px-0">
                        <p class="lead my-3">You haven't enrolled in any course. search and enroll for courses!</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You haven't enrolled as a student, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student_enroll') }}" class="text-white fw-bold">Enroll</a></p>
                </div>
            </div>
        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}

templates/learning/student/course.html.twig
{% extends 'learning/index.html.twig' %}

{% block title %}{{ course.title }}{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}
            <h2> {{ course.title }}</h2>
            <div class="list-group">
                <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                    <div class="col-md-6 px-0">
                        <h1 class="display-4 fst-italic">Information</h1>
                        <p class="lead my-3">{{ course.description }}</p>
                      </div>
                </div>
            </div>
            {% if enrolled %}
                <div>
                    <h3>Outline</h3>
                    <div class="accordion" id="accordionExample">
                        {% for week in course.courseweeks %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingweeky{{ week.id }}">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseweeky{{ week.id }}" aria-expanded="true" aria-controls="collapseweeky{{ week.id }}">
                                        Week {{ week.cardinality}}
                                    </button>
                                </h2>
                                <div id="collapseweeky{{ week.id }}" class="accordion-collapse collapse show" aria-labelledby="headingweeky{{ week.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <div class="accordion" id="accordionlecture{{ week.id }}">
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="headinglecturepanel{{ week.id }}">
                                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapselecturepanel{{ week.id }}" aria-expanded="true" aria-controls="collapselecturepanel{{ week.id }}">
                                                        Lectures
                                                    </button>
                                                </h2>
                                                <div id="collapselecturepanel{{ week.id }}" class="accordion-collapse collapse show" aria-labelledby="headinglecturepanel{{ week.id }}" data-bs-parent="#accordionlecture{{ week.id }}">
                                                    <div class="accordion-body">
                                                        <ol class="list-group ">
                                                            {% for lecture in week.lectures %}
                                                                <a href="{{ path('app_student_lecture', {lecture: lecture.id}) }}" class="list-group-item d-flex justify-content-between align-items-start">
                                                                    <div class="ms-2 me-auto">
                                                                        <div class="fw-bold">{{ lecture.title }}</div>
                                                                    </div>
                                                                </a>
                                                            {% endfor %}
                                                        </ol>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="accordion" id="accordionassignment{{ week.id }}">
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="headingassignmentpanel{{ week.id }}">
                                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseassignmentpanel{{ week.id }}" aria-expanded="true" aria-controls="collapseassignmentpanel{{ week.id }}">
                                                        Assignments
                                                    </button>
                                                </h2>
                                                <div id="collapseassignmentpanel{{ week.id }}" class="accordion-collapse collapse show" aria-labelledby="headingassignmentpanel{{ week.id }}" data-bs-parent="#accordionassignment{{ week.id }}">
                                                    <div class="accordion-body">
                                                        <ol class="list-group ">
                                                            {% for assignment in week.Assignments %}
                                                                <a href="{{ path('app_student_assignment', {assignment: assignment.id}) }}" class="list-group-item d-flex justify-content-between align-items-start">
                                                                    <div class="ms-2 me-auto">
                                                                        <div class="fw-bold">{{ assignment.title }}</div>
                                                                    </div>
                                                                </a>
                                                            {% endfor %}
                                                        </ol>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <form method="post" action="{{ path('app_student_course_enroll', {course: course.id}) }}">
                <button class="btn btn-primary mb-3">Enroll</button>

            {% endif %}


        {% else %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You haven't enrolled as a student, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student_enroll') }}" class="text-white fw-bold">Enroll</a></p>
                </div>
            </div>
        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}

templates/learning/student/courses.html.twig
{% extends 'learning/index.html.twig' %}

{% block title %}My Courses{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}
            <h2> My Courses</h2>
            <div class="list-group">
                {% for course in app.user.student.courses %}
                <a href="{{ path('app_student_course', {course: course.id}) }}" class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ course.title }}</h5>
                        <small>Professor  {{ course.CourseHead.user.lastName }}</small>
                    </div>
                    <p class="mb-1">Department of {{ course.department.name }}</p>
                    <small>{{ course.assignments| length }} Assignments!</small>
                </a>
                {% else %}
                    <div class="col-md-6 px-0">
                        <p class="lead my-3">You haven't enrolled in any course. search and enroll for courses!</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You haven't enrolled as a student, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student_enroll') }}" class="text-white fw-bold">Enroll</a></p>
                </div>
            </div>
        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}

templates/learning/student/courses_search.html.twig
{% extends 'learning/index.html.twig' %}

{% block title %}Search Courses{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}
            <h2> Courses</h2>
            <div class="list-group">
                {% for course in courses %}
                <a href="{{ path('app_student_course', {course: course.id}) }}" class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ course.title }}</h5>
                        <small>{{ course.CourseHead.user.FirstName }} {{ course.CourseHead.user.LastName }}</small>
                    </div>
                    <p class="mb-1">Department of {{ course.department.name }}</p>
                    <small>{{ course.assignments| length }} Assignments!</small>
                </a>
                {% else %}
                    <div class="col-md-6 px-0">
                        <p class="lead my-3">No Courses Found!</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You haven't enrolled as a student, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student_enroll') }}" class="text-white fw-bold">Enroll</a></p>
                </div>
            </div>
        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}

templates/learning/student/enroll.html.twig
{% extends 'learning/index.html.twig' %}
{% block title %}Enroll{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}

            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You have already enrolled to the school, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student') }}" class="text-white fw-bold">Dashboard</a></p>
                </div>
            </div>
        {% else %}
        <form action="{{ path('app_student_enroll') }}" method="post">
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Faculty</label>
                <select class="form-select" aria-label="Default select example" aria-required="true" name="faculty">
                    <option value="" selected>Select Faculty</option>
                    {% for faculty in faculties %}
                    <option value={{ faculty.id }}>{{  faculty.Name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Department</label>
                <select class="form-select" aria-label="Default select example" aria-required="true" name="department">
                    <option value="" selected>Select Department</option>
                    {% for department in departments %}
                    <option value={{ department.id }}>{{  department.Name }}</option>
                    {% endfor %}
                </select>
            </div>
            <input class="button" type="submit" value="Register" />
        </form>

        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}

templates/learning/student/index.html.twig
{% extends 'learning/index.html.twig' %}

{% block title %}Dashboard{% endblock %}


{% block body %}
    {{ include('learning/student/header.html.twig') }}
    <main class="container">
        {% if app.user.student %}

            <div class="row mb-2">
                <div class="col-md-6">
                    <h3 class="mb-0">Courses</h3>
                    <ol class="list-group list-group-numbered">
                        {% for course in app.user.student.courses|slice(0,5) %}
                            <a href="{{ path('app_student_course', {course: course.id}) }}" class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">{{ course.title }}</div>
                                    {{ course.department.name }}
                                </div>
                                <span class="badge bg-primary rounded-pill">{{ course.assignments| length }} Assignments!</span>
                            </a>
                        {% else %}
                            <div class="col-md-6 px-0">
                                <h5 class="card-title">No Courses Registered!</h5>
                                <p class="lead mb-0"><a href="{{ path('app_student_courses') }}" class="text-black fw-bold">Enroll in a Course</a></p>
                            </div>
                        {% endfor %}
                    </ol>
                </div>
                <div class="col-md-6">
                    <h3 class="mb-0">Assignments</h3>
                    <ol class="list-group list-group-numbered">
                    {% for assignment in assignments|slice(0,5) %}
                        <a href="{{ path('app_student_assignment', {assignment: assignment.id}) }}" class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">{{ assignment.title }}</div>
                                {{ assignment.course.title }}
                            </div>
                        </a>
                    {% else %}
                        <div class="col-md-6 px-0">
                            <p class="lead my-3">No Assignments!</p>
                        </div>
                    {% endfor %}
                    </ol>


                </div>
            </div>
        {% else %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <div class="col-md-6 px-0">
                    <p class="lead my-3">You haven't enrolled as a student, click the link below to start.</p>
                    <p class="lead mb-0"><a href="{{ path('app_student_enroll') }}" class="text-white fw-bold">Enroll</a></p>
                </div>
            </div>
        {% endif %}
        <!--<div class="p-4 p-md-5 mb-4 text-white rounded bg-white"></div>-->


    </main>

{% endblock %}